#!/usr/bin/env python3
import os
import sys


def main(argv=None):
    # Ensure local code path is on sys.path so we don't need PYTHONPATH
    root = os.path.dirname(os.path.abspath(__file__))
    code_path = os.path.join(root, "code")
    if code_path not in sys.path:
        sys.path.insert(0, code_path)

    if argv is None:
        argv = sys.argv[1:]

    from helix.cli import main as cli_main

    raise SystemExit(cli_main(argv))


if __name__ == "__main__":
    main()


